local_name: forum.service.subscribe # 本地服务名
k8s_service_name: forum.subscribe-be # k8s 服务名
runmode: debug                 # 开发模式, debug, release, test 部署时环境变量覆盖
redis:
  addr: 127.0.0.1:6379
  password:
tracing:
  jager: localhost:6831 # opentracing
#db:  # DB 配置 部署时环境变量覆盖
#  name: forum
#  addr: localhost:3306
#  username: root
#  password: 12345678
