// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: post.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HandleReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleReportRequest) Reset() {
	*x = HandleReportRequest{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleReportRequest) ProtoMessage() {}

func (x *HandleReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleReportRequest.ProtoReflect.Descriptor instead.
func (*HandleReportRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *HandleReportRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HandleReportRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ListReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        uint32                 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Pagination    bool                   `protobuf:"varint,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportRequest) Reset() {
	*x = ListReportRequest{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportRequest) ProtoMessage() {}

func (x *ListReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportRequest.ProtoReflect.Descriptor instead.
func (*ListReportRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *ListReportRequest) GetLastId() uint32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListReportRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListReportRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReportRequest) GetPagination() bool {
	if x != nil {
		return x.Pagination
	}
	return false
}

type Report struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId             uint32                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId             uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cause              string                 `protobuf:"bytes,4,opt,name=cause,proto3" json:"cause,omitempty"`
	TypeName           string                 `protobuf:"bytes,5,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	CreateTime         string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UserAvatar         string                 `protobuf:"bytes,7,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	UserName           string                 `protobuf:"bytes,8,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	BeReportedUserId   uint32                 `protobuf:"varint,9,opt,name=be_reported_user_id,json=beReportedUserId,proto3" json:"be_reported_user_id,omitempty"`
	BeReportedUserName string                 `protobuf:"bytes,10,opt,name=be_reported_user_name,json=beReportedUserName,proto3" json:"be_reported_user_name,omitempty"`
	BeReportedContent  string                 `protobuf:"bytes,11,opt,name=be_reported_content,json=beReportedContent,proto3" json:"be_reported_content,omitempty"`
	Category           string                 `protobuf:"bytes,12,opt,name=category,proto3" json:"category,omitempty"`
	TargetId           uint32                 `protobuf:"varint,13,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *Report) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Report) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Report) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Report) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *Report) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Report) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Report) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *Report) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Report) GetBeReportedUserId() uint32 {
	if x != nil {
		return x.BeReportedUserId
	}
	return 0
}

func (x *Report) GetBeReportedUserName() string {
	if x != nil {
		return x.BeReportedUserName
	}
	return ""
}

func (x *Report) GetBeReportedContent() string {
	if x != nil {
		return x.BeReportedContent
	}
	return ""
}

func (x *Report) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Report) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type ListReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportResponse) Reset() {
	*x = ListReportResponse{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportResponse) ProtoMessage() {}

func (x *ListReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportResponse.ProtoReflect.Descriptor instead.
func (*ListReportResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *ListReportResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Cause         string                 `protobuf:"bytes,4,opt,name=cause,proto3" json:"cause,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReportRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReportRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateReportRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CreateReportRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CreateReportRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListPopularTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopularTagRequest) Reset() {
	*x = ListPopularTagRequest{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopularTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularTagRequest) ProtoMessage() {}

func (x *ListPopularTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularTagRequest.ProtoReflect.Descriptor instead.
func (*ListPopularTagRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *ListPopularTagRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type LikeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeItem) Reset() {
	*x = LikeItem{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeItem) ProtoMessage() {}

func (x *LikeItem) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeItem.ProtoReflect.Descriptor instead.
func (*LikeItem) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *LikeItem) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *LikeItem) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Item          *LikeItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *LikeRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeRequest) GetItem() *LikeItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint32                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	FatherId      uint32                 `protobuf:"varint,3,opt,name=father_id,json=fatherId,proto3" json:"father_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatorId     uint32                 `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCommentRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CreateCommentRequest) GetFatherId() uint32 {
	if x != nil {
		return x.FatherId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateCommentRequest) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

type CommentInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeName          string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Content           string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	FatherId          uint32                 `protobuf:"varint,4,opt,name=father_id,json=fatherId,proto3" json:"father_id,omitempty"`
	Time              string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	CreatorId         uint32                 `protobuf:"varint,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName       string                 `protobuf:"bytes,7,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorAvatar     string                 `protobuf:"bytes,8,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	LikeNum           uint32                 `protobuf:"varint,9,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsLiked           bool                   `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	BeRepliedUserId   uint32                 `protobuf:"varint,11,opt,name=be_replied_user_id,json=beRepliedUserId,proto3" json:"be_replied_user_id,omitempty"`
	BeRepliedUserName string                 `protobuf:"bytes,12,opt,name=be_replied_user_name,json=beRepliedUserName,proto3" json:"be_replied_user_name,omitempty"`
	FatherContent     string                 `protobuf:"bytes,13,opt,name=father_content,json=fatherContent,proto3" json:"father_content,omitempty"`
	ImgUrl            string                 `protobuf:"bytes,14,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *CommentInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetFatherId() uint32 {
	if x != nil {
		return x.FatherId
	}
	return 0
}

func (x *CommentInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *CommentInfo) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CommentInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *CommentInfo) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *CommentInfo) GetLikeNum() uint32 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *CommentInfo) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *CommentInfo) GetBeRepliedUserId() uint32 {
	if x != nil {
		return x.BeRepliedUserId
	}
	return 0
}

func (x *CommentInfo) GetBeRepliedUserName() string {
	if x != nil {
		return x.BeRepliedUserName
	}
	return ""
}

func (x *CommentInfo) GetFatherContent() string {
	if x != nil {
		return x.FatherContent
	}
	return ""
}

func (x *CommentInfo) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteItemRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *DeleteItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdatePostInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CompiledContent string                 `protobuf:"bytes,3,opt,name=compiled_content,json=compiledContent,proto3" json:"compiled_content,omitempty"`
	UserId          uint32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Summary         string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags            []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Domain          string                 `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePostInfoRequest) Reset() {
	*x = UpdatePostInfoRequest{}
	mi := &file_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostInfoRequest) ProtoMessage() {}

func (x *UpdatePostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostInfoRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePostInfoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePostInfoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostInfoRequest) GetCompiledContent() string {
	if x != nil {
		return x.CompiledContent
	}
	return ""
}

func (x *UpdatePostInfoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostInfoRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdatePostInfoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostInfoRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdatePostInfoRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdatePostInfoRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreatePostRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ContentType     string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CompiledContent string                 `protobuf:"bytes,7,opt,name=compiled_content,json=compiledContent,proto3" json:"compiled_content,omitempty"`
	Summary         string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags            []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreatePostRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreatePostRequest) GetCompiledContent() string {
	if x != nil {
		return x.CompiledContent
	}
	return ""
}

func (x *CreatePostRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_post_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{15}
}

type CreateOrRemoveCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TypeName      string                 `protobuf:"bytes,4,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrRemoveCollectionResponse) Reset() {
	*x = CreateOrRemoveCollectionResponse{}
	mi := &file_post_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrRemoveCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrRemoveCollectionResponse) ProtoMessage() {}

func (x *CreateOrRemoveCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrRemoveCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateOrRemoveCollectionResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{16}
}

func (x *CreateOrRemoveCollectionResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOrRemoveCollectionResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrRemoveCollectionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateOrRemoveCollectionResponse) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FatherContent string                 `protobuf:"bytes,3,opt,name=father_content,json=fatherContent,proto3" json:"father_content,omitempty"`
	FatherUserId  uint32                 `protobuf:"varint,4,opt,name=father_user_id,json=fatherUserId,proto3" json:"father_user_id,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CreatorName   string                 `protobuf:"bytes,6,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorAvatar string                 `protobuf:"bytes,7,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	TypeName      string                 `protobuf:"bytes,8,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_post_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCommentResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentResponse) GetFatherContent() string {
	if x != nil {
		return x.FatherContent
	}
	return ""
}

func (x *CreateCommentResponse) GetFatherUserId() uint32 {
	if x != nil {
		return x.FatherUserId
	}
	return 0
}

func (x *CreateCommentResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *CreateCommentResponse) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *CreateCommentResponse) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *CreateCommentResponse) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type ListMainPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        uint32                 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	UserId        uint32                 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    bool                   `protobuf:"varint,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SearchContent string                 `protobuf:"bytes,8,opt,name=search_content,json=searchContent,proto3" json:"search_content,omitempty"`
	Filter        string                 `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMainPostRequest) Reset() {
	*x = ListMainPostRequest{}
	mi := &file_post_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMainPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMainPostRequest) ProtoMessage() {}

func (x *ListMainPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMainPostRequest.ProtoReflect.Descriptor instead.
func (*ListMainPostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{18}
}

func (x *ListMainPostRequest) GetLastId() uint32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListMainPostRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMainPostRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMainPostRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListMainPostRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListMainPostRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMainPostRequest) GetPagination() bool {
	if x != nil {
		return x.Pagination
	}
	return false
}

func (x *ListMainPostRequest) GetSearchContent() string {
	if x != nil {
		return x.SearchContent
	}
	return ""
}

func (x *ListMainPostRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListMainPostRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostResponse) Reset() {
	*x = ListPostResponse{}
	mi := &file_post_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostResponse) ProtoMessage() {}

func (x *ListPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostResponse.ProtoReflect.Descriptor instead.
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{19}
}

func (x *ListPostResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type Post struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Time            string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatorId       uint32                 `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName     string                 `protobuf:"bytes,6,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	Content         string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatorAvatar   string                 `protobuf:"bytes,8,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	CommentNum      uint32                 `protobuf:"varint,9,opt,name=comment_num,json=commentNum,proto3" json:"comment_num,omitempty"`
	LikeNum         uint32                 `protobuf:"varint,10,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsLiked         bool                   `protobuf:"varint,11,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsCollection    bool                   `protobuf:"varint,12,opt,name=is_collection,json=isCollection,proto3" json:"is_collection,omitempty"`
	ContentType     string                 `protobuf:"bytes,13,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CompiledContent string                 `protobuf:"bytes,14,opt,name=compiled_content,json=compiledContent,proto3" json:"compiled_content,omitempty"`
	Summary         string                 `protobuf:"bytes,15,opt,name=summary,proto3" json:"summary,omitempty"`
	CollectionNum   uint32                 `protobuf:"varint,16,opt,name=collection_num,json=collectionNum,proto3" json:"collection_num,omitempty"`
	Domain          string                 `protobuf:"bytes,17,opt,name=domain,proto3" json:"domain,omitempty"`
	Tags            []string               `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags,omitempty"`
	Comments        []*CommentInfo         `protobuf:"bytes,19,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{20}
}

func (x *Post) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Post) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Post) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Post) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *Post) GetCommentNum() uint32 {
	if x != nil {
		return x.CommentNum
	}
	return 0
}

func (x *Post) GetLikeNum() uint32 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *Post) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Post) GetIsCollection() bool {
	if x != nil {
		return x.IsCollection
	}
	return false
}

func (x *Post) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Post) GetCompiledContent() string {
	if x != nil {
		return x.CompiledContent
	}
	return ""
}

func (x *Post) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Post) GetCollectionNum() uint32 {
	if x != nil {
		return x.CollectionNum
	}
	return 0
}

func (x *Post) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_post_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{21}
}

func (x *Tags) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListPostPartInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        uint32                 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Id            uint32                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    bool                   `protobuf:"varint,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	TargetUserId  uint32                 `protobuf:"varint,7,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostPartInfoRequest) Reset() {
	*x = ListPostPartInfoRequest{}
	mi := &file_post_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostPartInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostPartInfoRequest) ProtoMessage() {}

func (x *ListPostPartInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostPartInfoRequest.ProtoReflect.Descriptor instead.
func (*ListPostPartInfoRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{22}
}

func (x *ListPostPartInfoRequest) GetLastId() uint32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListPostPartInfoRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPostPartInfoRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPostPartInfoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListPostPartInfoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPostPartInfoRequest) GetPagination() bool {
	if x != nil {
		return x.Pagination
	}
	return false
}

func (x *ListPostPartInfoRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type ListPostPartInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostPartInfo        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostPartInfoResponse) Reset() {
	*x = ListPostPartInfoResponse{}
	mi := &file_post_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostPartInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostPartInfoResponse) ProtoMessage() {}

func (x *ListPostPartInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostPartInfoResponse.ProtoReflect.Descriptor instead.
func (*ListPostPartInfoResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{23}
}

func (x *ListPostPartInfoResponse) GetPosts() []*PostPartInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

type PostPartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Time          string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	CreatorId     uint32                 `protobuf:"varint,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName   string                 `protobuf:"bytes,7,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorAvatar string                 `protobuf:"bytes,8,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	CommentNum    uint32                 `protobuf:"varint,9,opt,name=comment_num,json=commentNum,proto3" json:"comment_num,omitempty"`
	LikeNum       uint32                 `protobuf:"varint,10,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	CollectionNum uint32                 `protobuf:"varint,11,opt,name=collection_num,json=collectionNum,proto3" json:"collection_num,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPartInfo) Reset() {
	*x = PostPartInfo{}
	mi := &file_post_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPartInfo) ProtoMessage() {}

func (x *PostPartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPartInfo.ProtoReflect.Descriptor instead.
func (*PostPartInfo) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{24}
}

func (x *PostPartInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostPartInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostPartInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostPartInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PostPartInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *PostPartInfo) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *PostPartInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *PostPartInfo) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *PostPartInfo) GetCommentNum() uint32 {
	if x != nil {
		return x.CommentNum
	}
	return 0
}

func (x *PostPartInfo) GetLikeNum() uint32 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *PostPartInfo) GetCollectionNum() uint32 {
	if x != nil {
		return x.CollectionNum
	}
	return 0
}

func (x *PostPartInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_post_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteCollectionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UnReadPostNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnReadPostNum) Reset() {
	*x = UnReadPostNum{}
	mi := &file_post_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnReadPostNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnReadPostNum) ProtoMessage() {}

func (x *UnReadPostNum) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnReadPostNum.ProtoReflect.Descriptor instead.
func (*UnReadPostNum) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{26}
}

func (x *UnReadPostNum) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UnReadPostNum) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UnReadPostNumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnReadNum     []*UnReadPostNum       `protobuf:"bytes,1,rep,name=un_read_num,json=unReadNum,proto3" json:"un_read_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnReadPostNumResponse) Reset() {
	*x = UnReadPostNumResponse{}
	mi := &file_post_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnReadPostNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnReadPostNumResponse) ProtoMessage() {}

func (x *UnReadPostNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnReadPostNumResponse.ProtoReflect.Descriptor instead.
func (*UnReadPostNumResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{27}
}

func (x *UnReadPostNumResponse) GetUnReadNum() []*UnReadPostNum {
	if x != nil {
		return x.UnReadNum
	}
	return nil
}

type UpdateLastReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastReadRequest) Reset() {
	*x = UpdateLastReadRequest{}
	mi := &file_post_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastReadRequest) ProtoMessage() {}

func (x *UpdateLastReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastReadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLastReadRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateLastReadRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateLastReadRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\"$\n" +
	"\x12CreatePostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"=\n" +
	"\x13HandleReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"z\n" +
	"\x11ListReportRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\rR\x06lastId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1e\n" +
	"\n" +
	"pagination\x18\x04 \x01(\bR\n" +
	"pagination\"\xa7\x03\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\rR\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x14\n" +
	"\x05cause\x18\x04 \x01(\tR\x05cause\x12\x1b\n" +
	"\ttype_name\x18\x05 \x01(\tR\btypeName\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vuser_avatar\x18\a \x01(\tR\n" +
	"userAvatar\x12\x1b\n" +
	"\tuser_name\x18\b \x01(\tR\buserName\x12-\n" +
	"\x13be_reported_user_id\x18\t \x01(\rR\x10beReportedUserId\x121\n" +
	"\x15be_reported_user_name\x18\n" +
	" \x01(\tR\x12beReportedUserName\x12.\n" +
	"\x13be_reported_content\x18\v \x01(\tR\x11beReportedContent\x12\x1a\n" +
	"\bcategory\x18\f \x01(\tR\bcategory\x12\x1b\n" +
	"\ttarget_id\x18\r \x01(\rR\btargetId\"<\n" +
	"\x12ListReportResponse\x12&\n" +
	"\areports\x18\x01 \x03(\v2\f.post.ReportR\areports\"\x8d\x01\n" +
	"\x13CreateReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12\x14\n" +
	"\x05cause\x18\x04 \x01(\tR\x05cause\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"3\n" +
	"\x15ListPopularTagRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"D\n" +
	"\bLikeItem\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\"J\n" +
	"\vLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\x04item\x18\x02 \x01(\v2\x0e.post.LikeItemR\x04item\"\xbb\x01\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\rR\x06postId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12\x1b\n" +
	"\tfather_id\x18\x03 \x01(\rR\bfatherId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\rR\tcreatorId\x12\x17\n" +
	"\aimg_url\x18\x06 \x01(\tR\x06imgUrl\"\xc2\x03\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tfather_id\x18\x04 \x01(\rR\bfatherId\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x06 \x01(\rR\tcreatorId\x12!\n" +
	"\fcreator_name\x18\a \x01(\tR\vcreatorName\x12%\n" +
	"\x0ecreator_avatar\x18\b \x01(\tR\rcreatorAvatar\x12\x19\n" +
	"\blike_num\x18\t \x01(\rR\alikeNum\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\x12+\n" +
	"\x12be_replied_user_id\x18\v \x01(\rR\x0fbeRepliedUserId\x12/\n" +
	"\x14be_replied_user_name\x18\f \x01(\tR\x11beRepliedUserName\x12%\n" +
	"\x0efather_content\x18\r \x01(\tR\rfatherContent\x12\x17\n" +
	"\aimg_url\x18\x0e \x01(\tR\x06imgUrl\"2\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"Y\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\xfd\x01\n" +
	"\x15UpdatePostInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12)\n" +
	"\x10compiled_content\x18\x03 \x01(\tR\x0fcompiledContent\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\rR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x16\n" +
	"\x06domain\x18\t \x01(\tR\x06domain\"\x8c\x02\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12)\n" +
	"\x10compiled_content\x18\a \x01(\tR\x0fcompiledContent\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"\n" +
	"\n" +
	"\bResponse\"\x82\x01\n" +
	" CreateOrRemoveCollectionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\ttype_name\x18\x04 \x01(\tR\btypeName\"\x95\x02\n" +
	"\x15CreateCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12%\n" +
	"\x0efather_content\x18\x03 \x01(\tR\rfatherContent\x12$\n" +
	"\x0efather_user_id\x18\x04 \x01(\rR\ffatherUserId\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\x12!\n" +
	"\fcreator_name\x18\x06 \x01(\tR\vcreatorName\x12%\n" +
	"\x0ecreator_avatar\x18\a \x01(\tR\rcreatorAvatar\x12\x1b\n" +
	"\ttype_name\x18\b \x01(\tR\btypeName\"\x9a\x02\n" +
	"\x13ListMainPostRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\rR\x06lastId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\rR\x06userId\x12\x1e\n" +
	"\n" +
	"pagination\x18\a \x01(\bR\n" +
	"pagination\x12%\n" +
	"\x0esearch_content\x18\b \x01(\tR\rsearchContent\x12\x16\n" +
	"\x06filter\x18\t \x01(\tR\x06filter\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"4\n" +
	"\x10ListPostResponse\x12 \n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostR\x05posts\"\xc5\x04\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\rR\tcreatorId\x12!\n" +
	"\fcreator_name\x18\x06 \x01(\tR\vcreatorName\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12%\n" +
	"\x0ecreator_avatar\x18\b \x01(\tR\rcreatorAvatar\x12\x1f\n" +
	"\vcomment_num\x18\t \x01(\rR\n" +
	"commentNum\x12\x19\n" +
	"\blike_num\x18\n" +
	" \x01(\rR\alikeNum\x12\x19\n" +
	"\bis_liked\x18\v \x01(\bR\aisLiked\x12#\n" +
	"\ris_collection\x18\f \x01(\bR\fisCollection\x12!\n" +
	"\fcontent_type\x18\r \x01(\tR\vcontentType\x12)\n" +
	"\x10compiled_content\x18\x0e \x01(\tR\x0fcompiledContent\x12\x18\n" +
	"\asummary\x18\x0f \x01(\tR\asummary\x12%\n" +
	"\x0ecollection_num\x18\x10 \x01(\rR\rcollectionNum\x12\x16\n" +
	"\x06domain\x18\x11 \x01(\tR\x06domain\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\x12-\n" +
	"\bcomments\x18\x13 \x03(\v2\x11.post.CommentInfoR\bcomments\"\x1a\n" +
	"\x04Tags\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"\xcf\x01\n" +
	"\x17ListPostPartInfoRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\rR\x06lastId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\rR\x06userId\x12\x1e\n" +
	"\n" +
	"pagination\x18\x06 \x01(\bR\n" +
	"pagination\x12$\n" +
	"\x0etarget_user_id\x18\a \x01(\rR\ftargetUserId\"D\n" +
	"\x18ListPostPartInfoResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.post.PostPartInfoR\x05posts\"\xde\x02\n" +
	"\fPostPartInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x06 \x01(\rR\tcreatorId\x12!\n" +
	"\fcreator_name\x18\a \x01(\tR\vcreatorName\x12%\n" +
	"\x0ecreator_avatar\x18\b \x01(\tR\rcreatorAvatar\x12\x1f\n" +
	"\vcomment_num\x18\t \x01(\rR\n" +
	"commentNum\x12\x19\n" +
	"\blike_num\x18\n" +
	" \x01(\rR\alikeNum\x12%\n" +
	"\x0ecollection_num\x18\v \x01(\rR\rcollectionNum\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\")\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"=\n" +
	"\rUnReadPostNum\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"L\n" +
	"\x15UnReadPostNumResponse\x123\n" +
	"\vun_read_num\x18\x01 \x03(\v2\x13.post.UnReadPostNumR\tunReadNum\"L\n" +
	"\x15UpdateLastReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory2\xf9\t\n" +
	"\vPostService\x12A\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x18.post.CreatePostResponse\"\x00\x12&\n" +
	"\aGetPost\x12\r.post.Request\x1a\n" +
	".post.Post\"\x00\x12C\n" +
	"\fListMainPost\x12\x19.post.ListMainPostRequest\x1a\x16.post.ListPostResponse\"\x00\x12V\n" +
	"\x13ListUserCreatedPost\x12\x1d.post.ListPostPartInfoRequest\x1a\x1e.post.ListPostPartInfoResponse\"\x00\x12?\n" +
	"\x0eUpdatePostInfo\x12\x1b.post.UpdatePostInfoRequest\x1a\x0e.post.Response\"\x00\x121\n" +
	"\x0eSetQualityPost\x12\r.post.Request\x1a\x0e.post.Response\"\x00\x12@\n" +
	"\x10GetUnReadPostNum\x12\r.post.Request\x1a\x1b.post.UnReadPostNumResponse\"\x00\x12C\n" +
	"\x12UpdateLastReadTime\x12\x1b.post.UpdateLastReadRequest\x1a\x0e.post.Response\"\x00\x120\n" +
	"\n" +
	"GetComment\x12\r.post.Request\x1a\x11.post.CommentInfo\"\x00\x12J\n" +
	"\rCreateComment\x12\x1a.post.CreateCommentRequest\x1a\x1b.post.CreateCommentResponse\"\x00\x127\n" +
	"\n" +
	"DeleteItem\x12\x17.post.DeleteItemRequest\x1a\x0e.post.Response\"\x00\x129\n" +
	"\x12CreateOrRemoveLike\x12\x11.post.LikeRequest\x1a\x0e.post.Response\"\x00\x12S\n" +
	"\x10ListLikeByUserId\x12\x1d.post.ListPostPartInfoRequest\x1a\x1e.post.ListPostPartInfoResponse\"\x00\x12;\n" +
	"\x0eListPopularTag\x12\x1b.post.ListPopularTagRequest\x1a\n" +
	".post.Tags\"\x00\x12S\n" +
	"\x18CreateOrRemoveCollection\x12\r.post.Request\x1a&.post.CreateOrRemoveCollectionResponse\"\x00\x12Q\n" +
	"\x0eListCollection\x12\x1d.post.ListPostPartInfoRequest\x1a\x1e.post.ListPostPartInfoResponse\"\x00\x12;\n" +
	"\fCreateReport\x12\x19.post.CreateReportRequest\x1a\x0e.post.Response\"\x00\x12A\n" +
	"\n" +
	"ListReport\x12\x17.post.ListReportRequest\x1a\x18.post.ListReportResponse\"\x00\x12;\n" +
	"\fHandleReport\x12\x19.post.HandleReportRequest\x1a\x0e.post.Response\"\x00B\tZ\a./protob\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_post_proto_goTypes = []any{
	(*CreatePostResponse)(nil),               // 0: post.CreatePostResponse
	(*HandleReportRequest)(nil),              // 1: post.HandleReportRequest
	(*ListReportRequest)(nil),                // 2: post.ListReportRequest
	(*Report)(nil),                           // 3: post.Report
	(*ListReportResponse)(nil),               // 4: post.ListReportResponse
	(*CreateReportRequest)(nil),              // 5: post.CreateReportRequest
	(*ListPopularTagRequest)(nil),            // 6: post.ListPopularTagRequest
	(*LikeItem)(nil),                         // 7: post.LikeItem
	(*LikeRequest)(nil),                      // 8: post.LikeRequest
	(*CreateCommentRequest)(nil),             // 9: post.CreateCommentRequest
	(*CommentInfo)(nil),                      // 10: post.CommentInfo
	(*Request)(nil),                          // 11: post.Request
	(*DeleteItemRequest)(nil),                // 12: post.DeleteItemRequest
	(*UpdatePostInfoRequest)(nil),            // 13: post.UpdatePostInfoRequest
	(*CreatePostRequest)(nil),                // 14: post.CreatePostRequest
	(*Response)(nil),                         // 15: post.Response
	(*CreateOrRemoveCollectionResponse)(nil), // 16: post.CreateOrRemoveCollectionResponse
	(*CreateCommentResponse)(nil),            // 17: post.CreateCommentResponse
	(*ListMainPostRequest)(nil),              // 18: post.ListMainPostRequest
	(*ListPostResponse)(nil),                 // 19: post.ListPostResponse
	(*Post)(nil),                             // 20: post.Post
	(*Tags)(nil),                             // 21: post.Tags
	(*ListPostPartInfoRequest)(nil),          // 22: post.ListPostPartInfoRequest
	(*ListPostPartInfoResponse)(nil),         // 23: post.ListPostPartInfoResponse
	(*PostPartInfo)(nil),                     // 24: post.PostPartInfo
	(*DeleteCollectionRequest)(nil),          // 25: post.DeleteCollectionRequest
	(*UnReadPostNum)(nil),                    // 26: post.UnReadPostNum
	(*UnReadPostNumResponse)(nil),            // 27: post.UnReadPostNumResponse
	(*UpdateLastReadRequest)(nil),            // 28: post.UpdateLastReadRequest
}
var file_post_proto_depIdxs = []int32{
	3,  // 0: post.ListReportResponse.reports:type_name -> post.Report
	7,  // 1: post.LikeRequest.item:type_name -> post.LikeItem
	20, // 2: post.ListPostResponse.posts:type_name -> post.Post
	10, // 3: post.Post.comments:type_name -> post.CommentInfo
	24, // 4: post.ListPostPartInfoResponse.posts:type_name -> post.PostPartInfo
	26, // 5: post.UnReadPostNumResponse.un_read_num:type_name -> post.UnReadPostNum
	14, // 6: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	11, // 7: post.PostService.GetPost:input_type -> post.Request
	18, // 8: post.PostService.ListMainPost:input_type -> post.ListMainPostRequest
	22, // 9: post.PostService.ListUserCreatedPost:input_type -> post.ListPostPartInfoRequest
	13, // 10: post.PostService.UpdatePostInfo:input_type -> post.UpdatePostInfoRequest
	11, // 11: post.PostService.SetQualityPost:input_type -> post.Request
	11, // 12: post.PostService.GetUnReadPostNum:input_type -> post.Request
	28, // 13: post.PostService.UpdateLastReadTime:input_type -> post.UpdateLastReadRequest
	11, // 14: post.PostService.GetComment:input_type -> post.Request
	9,  // 15: post.PostService.CreateComment:input_type -> post.CreateCommentRequest
	12, // 16: post.PostService.DeleteItem:input_type -> post.DeleteItemRequest
	8,  // 17: post.PostService.CreateOrRemoveLike:input_type -> post.LikeRequest
	22, // 18: post.PostService.ListLikeByUserId:input_type -> post.ListPostPartInfoRequest
	6,  // 19: post.PostService.ListPopularTag:input_type -> post.ListPopularTagRequest
	11, // 20: post.PostService.CreateOrRemoveCollection:input_type -> post.Request
	22, // 21: post.PostService.ListCollection:input_type -> post.ListPostPartInfoRequest
	5,  // 22: post.PostService.CreateReport:input_type -> post.CreateReportRequest
	2,  // 23: post.PostService.ListReport:input_type -> post.ListReportRequest
	1,  // 24: post.PostService.HandleReport:input_type -> post.HandleReportRequest
	0,  // 25: post.PostService.CreatePost:output_type -> post.CreatePostResponse
	20, // 26: post.PostService.GetPost:output_type -> post.Post
	19, // 27: post.PostService.ListMainPost:output_type -> post.ListPostResponse
	23, // 28: post.PostService.ListUserCreatedPost:output_type -> post.ListPostPartInfoResponse
	15, // 29: post.PostService.UpdatePostInfo:output_type -> post.Response
	15, // 30: post.PostService.SetQualityPost:output_type -> post.Response
	27, // 31: post.PostService.GetUnReadPostNum:output_type -> post.UnReadPostNumResponse
	15, // 32: post.PostService.UpdateLastReadTime:output_type -> post.Response
	10, // 33: post.PostService.GetComment:output_type -> post.CommentInfo
	17, // 34: post.PostService.CreateComment:output_type -> post.CreateCommentResponse
	15, // 35: post.PostService.DeleteItem:output_type -> post.Response
	15, // 36: post.PostService.CreateOrRemoveLike:output_type -> post.Response
	23, // 37: post.PostService.ListLikeByUserId:output_type -> post.ListPostPartInfoResponse
	21, // 38: post.PostService.ListPopularTag:output_type -> post.Tags
	16, // 39: post.PostService.CreateOrRemoveCollection:output_type -> post.CreateOrRemoveCollectionResponse
	23, // 40: post.PostService.ListCollection:output_type -> post.ListPostPartInfoResponse
	15, // 41: post.PostService.CreateReport:output_type -> post.Response
	4,  // 42: post.PostService.ListReport:output_type -> post.ListReportResponse
	15, // 43: post.PostService.HandleReport:output_type -> post.Response
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
