basePath: /api/v1
definitions:
  FeedItem:
    properties:
      action:
        type: string
      date:
        type: string
      id:
        type: integer
      show_divider:
        description: 分割线
        type: boolean
      source:
        $ref: '#/definitions/Source'
      time:
        type: string
      user:
        $ref: '#/definitions/FeedUser'
    type: object
  FeedListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/FeedItem'
        type: array
    type: object
  FeedUser:
    properties:
      avatar_url:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  ListResponse:
    properties:
      count:
        type: integer
      list:
        items:
          $ref: '#/definitions/user'
        type: array
    type: object
  Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  Source:
    properties:
      id:
        type: integer
      kind:
        description: 类型，1 -> 团队，2 -> 项目，3 -> 文档，4 -> 文件，6 -> 进度（5 不使用）
        type: integer
      name:
        type: string
      project_id:
        type: integer
      project_name:
        type: string
    type: object
  StudentLoginRequest:
    properties:
      password:
        type: string
      student_id:
        type: string
    required:
    - password
    - student_id
    type: object
  StudentLoginResponse:
    properties:
      token:
        type: string
    type: object
  TeamLoginRequest:
    properties:
      oauth_code:
        type: string
    type: object
  TeamLoginResponse:
    properties:
      redirect_url:
        type: string
      token:
        type: string
    type: object
  UpdateInfoRequest:
    properties:
      avatar_url:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      signature:
        type: string
    type: object
  UserProfile:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
  chat.Id:
    properties:
      id:
        type: string
    type: object
  comment.Comment:
    properties:
      content:
        type: string
      create_time:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      father_id:
        type: integer
      id:
        type: integer
      is_liked:
        type: boolean
      like_num:
        type: integer
      type_name:
        type: string
    type: object
  comment.CreateRequest:
    properties:
      content:
        type: string
      father_id:
        type: integer
      post_id:
        type: integer
      type_name:
        description: sub-post -> 从帖; first-level -> 一级评论; second-level -> 其它级
        type: string
    required:
    - content
    - father_id
    - post_id
    - type_name
    type: object
  like.Item:
    properties:
      target_id:
        type: integer
      type_name:
        type: string
    required:
    - target_id
    - type_name
    type: object
  like.ListResponse:
    type: object
  post.Comment:
    properties:
      comment_num:
        type: integer
      content:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      id:
        type: integer
      is_liked:
        type: boolean
      like_num:
        type: integer
      replies:
        items:
          $ref: '#/definitions/post.info'
        type: array
      time:
        type: string
    type: object
  post.CreateRequest:
    properties:
      category:
        type: string
      content:
        type: string
      content_type:
        description: md or rtf
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      type_name:
        description: normal -> 团队外; muxi -> 团队内 (type_name暂时均填normal)
        type: string
    required:
    - category
    - content
    - content_type
    - title
    - type_name
    type: object
  post.GetPostResponse:
    properties:
      category:
        type: string
      comment_num:
        type: integer
      content:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      id:
        type: integer
      is_collection:
        type: boolean
      is_liked:
        type: boolean
      like_num:
        type: integer
      sub_posts:
        items:
          $ref: '#/definitions/post.SubPost'
        type: array
      tags:
        items:
          type: string
        type: array
      time:
        type: string
      title:
        type: string
    type: object
  post.Post:
    properties:
      category:
        type: string
      comment_num:
        type: integer
      comments:
        items:
          $ref: '#/definitions/comment.Comment'
        type: array
      content:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      id:
        type: integer
      is_collection:
        type: boolean
      is_liked:
        type: boolean
      like_num:
        type: integer
      tags:
        items:
          type: string
        type: array
      time:
        type: string
      title:
        type: string
    type: object
  post.SubPost:
    properties:
      comment_num:
        type: integer
      comments:
        items:
          $ref: '#/definitions/post.Comment'
        type: array
      content:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      id:
        type: integer
      is_liked:
        type: boolean
      like_num:
        type: integer
      time:
        type: string
    type: object
  post.UpdateInfoRequest:
    properties:
      category:
        type: string
      content:
        type: string
      id:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    required:
    - category
    - content
    - id
    - tags
    - title
    type: object
  post.info:
    properties:
      comment_num:
        type: integer
      content:
        type: string
      creator_avatar:
        type: string
      creator_id:
        type: integer
      creator_name:
        type: string
      id:
        type: integer
      is_liked:
        type: boolean
      like_num:
        type: integer
      time:
        type: string
    type: object
  user:
    properties:
      avatar:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
host: forum.muxixyz.com
info:
  contact: {}
  description: The gateway of forum
  title: forum-gateway
  version: "1.0"
paths:
  /auth/login/student:
    post:
      consumes:
      - application/json
      description: login the student-forum
      parameters:
      - description: login_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/StudentLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudentLoginResponse'
      summary: 学生登录 api
      tags:
      - auth
  /auth/login/team:
    post:
      consumes:
      - application/json
      description: login the team-forum
      parameters:
      - description: login_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/TeamLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TeamLoginResponse'
      summary: 团队登录 api
      tags:
      - auth
  /chat:
    get:
      consumes:
      - application/json
      description: 该用户发送信息前先获取自己的uuid，并放入query(id=?)，有效期24h
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/chat.Id'
      summary: 获取该用户的uuid
      tags:
      - chat
  /chat/ws:
    get:
      description: 建立 WebSocket 连接
      parameters:
      - description: uuid
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: WebSocket
      tags:
      - chat
  /comment:
    post:
      consumes:
      - application/json
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: create_comment_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/comment.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 创建评论/从帖 api
      tags:
      - comment
  /comment/{comment_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: comment_id
        in: path
        name: comment_id
        required: true
        type: integer
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 删除评论 api
      tags:
      - comment
    get:
      consumes:
      - application/json
      description: 'typeName: first-level -> 一级评论; second-level -> 其它级'
      parameters:
      - description: comment_id
        in: path
        name: comment_id
        required: true
        type: integer
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.Comment'
      summary: 获取评论 api
      tags:
      - comment
  /feed/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: last_id
        in: query
        name: last_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/FeedListResponse'
      summary: list 此用户的动态 api
      tags:
      - feed
  /like:
    post:
      consumes:
      - application/json
      description: 'TypeName: post or comment'
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: like_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/like.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 点赞/取消点赞 api
      tags:
      - like
  /like/list:
    get:
      consumes:
      - application/json
      description: 'TypeName: post or comment'
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/like.ListResponse'
      summary: 获取用户点赞列表 api
      tags:
      - like
  /post:
    post:
      consumes:
      - application/json
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: create_post_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/post.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 创建帖子 api
      tags:
      - post
    put:
      consumes:
      - application/json
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: update_info_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/post.UpdateInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 修改帖子信息 api
      tags:
      - post
  /post/{post_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: post_id
        in: path
        name: post_id
        required: true
        type: integer
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 删除帖子 api
      tags:
      - post
    get:
      consumes:
      - application/json
      parameters:
      - description: post_id
        in: path
        name: post_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.GetPostResponse'
      summary: 获取帖子 api
      tags:
      - post
  /post/list/{type_name}:
    get:
      consumes:
      - application/json
      description: 'type_name : normal -> 团队外; muxi -> 团队内 (type_name暂时均填normal);
        根据category获取主帖list'
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: last_id
        in: query
        name: last_id
        type: integer
      - description: type_name
        in: path
        name: type_name
        required: true
        type: string
      - description: category
        in: query
        name: category
        type: string
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/post.Post'
            type: array
      summary: list 主帖 api
      tags:
      - post
  /post/popular_tags:
    get:
      consumes:
      - application/json
      description: 降序
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: list 热门tags api
      tags:
      - post
  /user:
    put:
      consumes:
      - application/json
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: update_info_request
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/UpdateInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
      summary: 修改用户个人信息 api
      tags:
      - user
  /user/list/{group_id}/{team_id}:
    get:
      consumes:
      - application/json
      description: 通过 group 和 team 获取 user_list
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: last_id
        in: query
        name: last_id
        type: integer
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: group_id
        in: path
        name: group_id
        required: true
        type: integer
      - description: team_id
        in: path
        name: team_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ListResponse'
      summary: list user api
      tags:
      - user
  /user/myprofile:
    get:
      consumes:
      - application/json
      description: 获取 my 完整 user 信息
      parameters:
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserProfile'
      summary: get 我的 profile api
      tags:
      - user
  /user/profile/{id}:
    get:
      consumes:
      - application/json
      description: '通过 userId 获取完整 user 信息（权限: Normal-普通学生用户; NormalAdmin-学生管理员; Muxi-团队成员;
        MuxiAdmin-团队管理员; SuperAdmin-超级管理员）'
      parameters:
      - description: user_id
        in: path
        name: id
        required: true
        type: integer
      - description: token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserProfile'
      summary: 获取用户 profile api
      tags:
      - user
swagger: "2.0"
tags:
- description: 用户服务
  name: user
- description: 认证服务
  name: auth
- description: 聊天服务
  name: chat
- description: 帖子服务
  name: post
- description: 动态服务
  name: feed
