// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreatePrivateMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SendUserId     uint32                 `protobuf:"varint,1,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	ReceiveUserId  uint32                 `protobuf:"varint,2,opt,name=receive_user_id,json=receiveUserId,proto3" json:"receive_user_id,omitempty"`
	PostId         uint32                 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId      uint32                 `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	PostTitle      string                 `protobuf:"bytes,7,opt,name=post_title,json=postTitle,proto3" json:"post_title,omitempty"`
	CommentContent string                 `protobuf:"bytes,8,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"` // 回复评论时，显示被回复的评论
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePrivateMessageRequest) Reset() {
	*x = CreatePrivateMessageRequest{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateMessageRequest) ProtoMessage() {}

func (x *CreatePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrivateMessageRequest) GetSendUserId() uint32 {
	if x != nil {
		return x.SendUserId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetReceiveUserId() uint32 {
	if x != nil {
		return x.ReceiveUserId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePrivateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePrivateMessageRequest) GetPostTitle() string {
	if x != nil {
		return x.PostTitle
	}
	return ""
}

func (x *CreatePrivateMessageRequest) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

type DeletePrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrivateMessageRequest) Reset() {
	*x = DeletePrivateMessageRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrivateMessageRequest) ProtoMessage() {}

func (x *DeletePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*DeletePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePrivateMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeletePrivateMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageRequest) Reset() {
	*x = ListMessageRequest{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageRequest) ProtoMessage() {}

func (x *ListMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageRequest.ProtoReflect.Descriptor instead.
func (*ListMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMessageRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessageRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SendUserId     string                 `protobuf:"bytes,2,opt,name=send_user_id,json=sendUserId,proto3" json:"send_user_id,omitempty"`
	PostId         string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId      string                 `protobuf:"bytes,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	PostTitle      string                 `protobuf:"bytes,7,opt,name=post_title,json=postTitle,proto3" json:"post_title,omitempty"`
	CommentContent string                 `protobuf:"bytes,8,opt,name=comment_content,json=commentContent,proto3" json:"comment_content,omitempty"` // 回复评论时，显示被回复的评论内容
	Avatar         string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	SenderName     string                 `protobuf:"bytes,10,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Read           bool                   `protobuf:"varint,11,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSendUserId() string {
	if x != nil {
		return x.SendUserId
	}
	return ""
}

func (x *Message) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Message) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetPostTitle() string {
	if x != nil {
		return x.PostTitle
	}
	return ""
}

func (x *Message) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *Message) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListPrivateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateMessageResponse) Reset() {
	*x = ListPrivateMessageResponse{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateMessageResponse) ProtoMessage() {}

func (x *ListPrivateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateMessageResponse.ProtoReflect.Descriptor instead.
func (*ListPrivateMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListPrivateMessageResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageResponse) Reset() {
	*x = ListMessageResponse{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageResponse) ProtoMessage() {}

func (x *ListMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageResponse.ProtoReflect.Descriptor instead.
func (*ListMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessageResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StudentLoginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StudentId        string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Action           string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	SessionId        string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Captcha          string                 `protobuf:"bytes,5,opt,name=captcha,proto3" json:"captcha,omitempty"`
	SecondAuthMethod string                 `protobuf:"bytes,6,opt,name=second_auth_method,json=secondAuthMethod,proto3" json:"second_auth_method,omitempty"`
	SecondAuthCode   string                 `protobuf:"bytes,7,opt,name=second_auth_code,json=secondAuthCode,proto3" json:"second_auth_code,omitempty"`
	Provider         string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	OauthCode        string                 `protobuf:"bytes,9,opt,name=oauth_code,json=oauthCode,proto3" json:"oauth_code,omitempty"`
	CallbackUrl      string                 `protobuf:"bytes,10,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudentLoginRequest) Reset() {
	*x = StudentLoginRequest{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentLoginRequest) ProtoMessage() {}

func (x *StudentLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentLoginRequest.ProtoReflect.Descriptor instead.
func (*StudentLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *StudentLoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *StudentLoginRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StudentLoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StudentLoginRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *StudentLoginRequest) GetSecondAuthMethod() string {
	if x != nil {
		return x.SecondAuthMethod
	}
	return ""
}

func (x *StudentLoginRequest) GetSecondAuthCode() string {
	if x != nil {
		return x.SecondAuthCode
	}
	return ""
}

func (x *StudentLoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StudentLoginRequest) GetOauthCode() string {
	if x != nil {
		return x.OauthCode
	}
	return ""
}

func (x *StudentLoginRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type UpdateInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *UserInfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfoRequest) Reset() {
	*x = UpdateInfoRequest{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfoRequest) ProtoMessage() {}

func (x *UpdateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInfoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInfoRequest) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ViewerId      uint32                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequest) GetViewerId() uint32 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUserId  uint32                 `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *FollowRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type FollowResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing    bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	FollowingCount uint32                 `protobuf:"varint,2,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowerCount  uint32                 `protobuf:"varint,3,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *FollowResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *FollowResponse) GetFollowingCount() uint32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *FollowResponse) GetFollowerCount() uint32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewerId      uint32                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *FollowListRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowListRequest) GetViewerId() uint32 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *FollowListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FollowListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FollowListUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Signature      string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	FollowingCount uint32                 `protobuf:"varint,6,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowerCount  uint32                 `protobuf:"varint,7,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	IsFollowing    bool                   `protobuf:"varint,8,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowListUser) Reset() {
	*x = FollowListUser{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListUser) ProtoMessage() {}

func (x *FollowListUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListUser.ProtoReflect.Descriptor instead.
func (*FollowListUser) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *FollowListUser) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowListUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FollowListUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FollowListUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FollowListUser) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FollowListUser) GetFollowingCount() uint32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *FollowListUser) GetFollowerCount() uint32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *FollowListUser) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type FollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*FollowListUser      `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListResponse) Reset() {
	*x = FollowListResponse{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResponse) ProtoMessage() {}

func (x *FollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResponse.ProtoReflect.Descriptor instead.
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *FollowListResponse) GetUsers() []*FollowListUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetInfoRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TeamLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthCode     string                 `protobuf:"bytes,1,opt,name=oauth_code,json=oauthCode,proto3" json:"oauth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamLoginRequest) Reset() {
	*x = TeamLoginRequest{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLoginRequest) ProtoMessage() {}

func (x *TeamLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLoginRequest.ProtoReflect.Descriptor instead.
func (*TeamLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *TeamLoginRequest) GetOauthCode() string {
	if x != nil {
		return x.OauthCode
	}
	return ""
}

type LoginResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Token                      string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RedirectUrl                string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	SessionId                  string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status                     string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message                    string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CaptchaImageBase64         string                 `protobuf:"bytes,6,opt,name=captcha_image_base64,json=captchaImageBase64,proto3" json:"captcha_image_base64,omitempty"`
	AvailableSecondAuthMethods []string               `protobuf:"bytes,7,rep,name=available_second_auth_methods,json=availableSecondAuthMethods,proto3" json:"available_second_auth_methods,omitempty"`
	CurrentSecondAuthMethod    string                 `protobuf:"bytes,8,opt,name=current_second_auth_method,json=currentSecondAuthMethod,proto3" json:"current_second_auth_method,omitempty"`
	SecondAuthSmsTarget        string                 `protobuf:"bytes,9,opt,name=second_auth_sms_target,json=secondAuthSmsTarget,proto3" json:"second_auth_sms_target,omitempty"`
	SecondAuthEmailTarget      string                 `protobuf:"bytes,10,opt,name=second_auth_email_target,json=secondAuthEmailTarget,proto3" json:"second_auth_email_target,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetCaptchaImageBase64() string {
	if x != nil {
		return x.CaptchaImageBase64
	}
	return ""
}

func (x *LoginResponse) GetAvailableSecondAuthMethods() []string {
	if x != nil {
		return x.AvailableSecondAuthMethods
	}
	return nil
}

func (x *LoginResponse) GetCurrentSecondAuthMethod() string {
	if x != nil {
		return x.CurrentSecondAuthMethod
	}
	return ""
}

func (x *LoginResponse) GetSecondAuthSmsTarget() string {
	if x != nil {
		return x.SecondAuthSmsTarget
	}
	return ""
}

func (x *LoginResponse) GetSecondAuthEmailTarget() string {
	if x != nil {
		return x.SecondAuthEmailTarget
	}
	return ""
}

type UserInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl                 string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Signature                 string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	IsPublicCollectionAndLike bool                   `protobuf:"varint,6,opt,name=is_public_collection_and_like,json=isPublicCollectionAndLike,proto3" json:"is_public_collection_and_like,omitempty"`
	IsPublicFeed              bool                   `protobuf:"varint,7,opt,name=is_public_feed,json=isPublicFeed,proto3" json:"is_public_feed,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserInfo) GetIsPublicCollectionAndLike() bool {
	if x != nil {
		return x.IsPublicCollectionAndLike
	}
	return false
}

func (x *UserInfo) GetIsPublicFeed() bool {
	if x != nil {
		return x.IsPublicFeed
	}
	return false
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserInfoResponse) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type UserProfile struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                      string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Avatar                    string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                     string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Signature                 string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	IsPublicFeed              bool                   `protobuf:"varint,7,opt,name=is_public_feed,json=isPublicFeed,proto3" json:"is_public_feed,omitempty"`
	IsPublicCollectionAndLike bool                   `protobuf:"varint,8,opt,name=is_public_collection_and_like,json=isPublicCollectionAndLike,proto3" json:"is_public_collection_and_like,omitempty"`
	FollowingCount            uint32                 `protobuf:"varint,9,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowerCount             uint32                 `protobuf:"varint,10,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	IsFollowing               bool                   `protobuf:"varint,11,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	StudentId                 string                 `protobuf:"bytes,12,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *UserProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserProfile) GetIsPublicFeed() bool {
	if x != nil {
		return x.IsPublicFeed
	}
	return false
}

func (x *UserProfile) GetIsPublicCollectionAndLike() bool {
	if x != nil {
		return x.IsPublicCollectionAndLike
	}
	return false
}

func (x *UserProfile) GetFollowingCount() uint32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *UserProfile) GetFollowerCount() uint32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *UserProfile) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *UserProfile) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        uint32                 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *ListRequest) GetLastId() uint32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	List          []*User                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListResponse) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{24}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{25}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetUserIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdentityRequest) Reset() {
	*x = GetUserIdentityRequest{}
	mi := &file_proto_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdentityRequest) ProtoMessage() {}

func (x *GetUserIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetUserIdentityRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserIdentityRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdentityResponse) Reset() {
	*x = GetUserIdentityResponse{}
	mi := &file_proto_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdentityResponse) ProtoMessage() {}

func (x *GetUserIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetUserIdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserIdentityResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserIdentityResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\"I\n" +
	"\x14CreateMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x02\n" +
	"\x1bCreatePrivateMessageRequest\x12 \n" +
	"\fsend_user_id\x18\x01 \x01(\rR\n" +
	"sendUserId\x12&\n" +
	"\x0freceive_user_id\x18\x02 \x01(\rR\rreceiveUserId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\rR\x06postId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\rR\tcommentId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"post_title\x18\a \x01(\tR\tpostTitle\x12'\n" +
	"\x0fcomment_content\x18\b \x01(\tR\x0ecommentContent\"F\n" +
	"\x1bDeletePrivateMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"[\n" +
	"\x12ListMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\xd5\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\fsend_user_id\x18\x02 \x01(\tR\n" +
	"sendUserId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"post_title\x18\a \x01(\tR\tpostTitle\x12'\n" +
	"\x0fcomment_content\x18\b \x01(\tR\x0ecommentContent\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x1f\n" +
	"\vsender_name\x18\n" +
	" \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04read\x18\v \x01(\bR\x04read\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"G\n" +
	"\x1aListPrivateMessageResponse\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.user.MessageR\bmessages\"1\n" +
	"\x13ListMessageResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"\xd7\x02\n" +
	"\x13StudentLoginRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\acaptcha\x18\x05 \x01(\tR\acaptcha\x12,\n" +
	"\x12second_auth_method\x18\x06 \x01(\tR\x10secondAuthMethod\x12(\n" +
	"\x10second_auth_code\x18\a \x01(\tR\x0esecondAuthCode\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"oauth_code\x18\t \x01(\tR\toauthCode\x12!\n" +
	"\fcallback_url\x18\n" +
	" \x01(\tR\vcallbackUrl\"G\n" +
	"\x11UpdateInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\"\n" +
	"\x04info\x18\x02 \x01(\v2\x0e.user.UserInfoR\x04info\"9\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\rR\bviewerId\"N\n" +
	"\rFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\rR\ftargetUserId\"\x83\x01\n" +
	"\x0eFollowResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\x12'\n" +
	"\x0ffollowing_count\x18\x02 \x01(\rR\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\x03 \x01(\rR\rfollowerCount\"w\n" +
	"\x11FollowListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\rR\bviewerId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"\xf1\x01\n" +
	"\x0eFollowListUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12'\n" +
	"\x0ffollowing_count\x18\x06 \x01(\rR\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\a \x01(\rR\rfollowerCount\x12!\n" +
	"\fis_following\x18\b \x01(\bR\visFollowing\"@\n" +
	"\x12FollowListResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.user.FollowListUserR\x05users\"\"\n" +
	"\x0eGetInfoRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"W\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"1\n" +
	"\x10TeamLoginRequest\x12\x1d\n" +
	"\n" +
	"oauth_code\x18\x01 \x01(\tR\toauthCode\"\xb9\x03\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x120\n" +
	"\x14captcha_image_base64\x18\x06 \x01(\tR\x12captchaImageBase64\x12A\n" +
	"\x1davailable_second_auth_methods\x18\a \x03(\tR\x1aavailableSecondAuthMethods\x12;\n" +
	"\x1acurrent_second_auth_method\x18\b \x01(\tR\x17currentSecondAuthMethod\x123\n" +
	"\x16second_auth_sms_target\x18\t \x01(\tR\x13secondAuthSmsTarget\x127\n" +
	"\x18second_auth_email_target\x18\n" +
	" \x01(\tR\x15secondAuthEmailTarget\"\xe9\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12@\n" +
	"\x1dis_public_collection_and_like\x18\x06 \x01(\bR\x19isPublicCollectionAndLike\x12$\n" +
	"\x0eis_public_feed\x18\a \x01(\bR\fisPublicFeed\"6\n" +
	"\x10UserInfoResponse\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04list\"\x8b\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12$\n" +
	"\x0eis_public_feed\x18\a \x01(\bR\fisPublicFeed\x12@\n" +
	"\x1dis_public_collection_and_like\x18\b \x01(\bR\x19isPublicCollectionAndLike\x12'\n" +
	"\x0ffollowing_count\x18\t \x01(\rR\x0efollowingCount\x12%\n" +
	"\x0efollower_count\x18\n" +
	" \x01(\rR\rfollowerCount\x12!\n" +
	"\fis_following\x18\v \x01(\bR\visFollowing\x12\x1d\n" +
	"\n" +
	"student_id\x18\f \x01(\tR\tstudentId\"h\n" +
	"\vListRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\rR\x06lastId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"D\n" +
	"\fListResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x1e\n" +
	"\x04list\x18\x02 \x03(\v2\n" +
	".user.UserR\x04list\"\t\n" +
	"\aRequest\"\n" +
	"\n" +
	"\bResponse\"\x8b\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"1\n" +
	"\x16GetUserIdentityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"Q\n" +
	"\x17GetUserIdentityResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId2\xc0\b\n" +
	"\vUserService\x12:\n" +
	"\tTeamLogin\x12\x16.user.TeamLoginRequest\x1a\x13.user.LoginResponse\"\x00\x12@\n" +
	"\fStudentLogin\x12\x19.user.StudentLoginRequest\x1a\x13.user.LoginResponse\"\x00\x129\n" +
	"\aGetInfo\x12\x14.user.GetInfoRequest\x1a\x16.user.UserInfoResponse\"\x00\x123\n" +
	"\n" +
	"GetProfile\x12\x10.user.GetRequest\x1a\x11.user.UserProfile\"\x00\x12;\n" +
	"\fToggleFollow\x12\x13.user.FollowRequest\x1a\x14.user.FollowResponse\"\x00\x12D\n" +
	"\rListFollowing\x12\x17.user.FollowListRequest\x1a\x18.user.FollowListResponse\"\x00\x12D\n" +
	"\rListFollowers\x12\x17.user.FollowListRequest\x1a\x18.user.FollowListResponse\"\x00\x12/\n" +
	"\x04List\x12\x11.user.ListRequest\x1a\x12.user.ListResponse\"\x00\x12D\n" +
	"\vListMessage\x12\x18.user.ListMessageRequest\x1a\x19.user.ListMessageResponse\"\x00\x12R\n" +
	"\x12ListPrivateMessage\x12\x18.user.ListMessageRequest\x1a .user.ListPrivateMessageResponse\"\x00\x12=\n" +
	"\rCreateMessage\x12\x1a.user.CreateMessageRequest\x1a\x0e.user.Response\"\x00\x12K\n" +
	"\x14CreatePrivateMessage\x12!.user.CreatePrivateMessageRequest\x1a\x0e.user.Response\"\x00\x12K\n" +
	"\x14DeletePrivateMessage\x12!.user.DeletePrivateMessageRequest\x1a\x0e.user.Response\"\x00\x12M\n" +
	"\x16MarkPrivateMessageRead\x12!.user.DeletePrivateMessageRequest\x1a\x0e.user.Response\"\x00\x127\n" +
	"\n" +
	"UpdateInfo\x12\x17.user.UpdateInfoRequest\x1a\x0e.user.Response\"\x00\x12N\n" +
	"\x0fGetUserIdentity\x12\x1c.user.GetUserIdentityRequest\x1a\x1d.user.GetUserIdentityResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_user_proto_goTypes = []any{
	(*CreateMessageRequest)(nil),        // 0: user.CreateMessageRequest
	(*CreatePrivateMessageRequest)(nil), // 1: user.CreatePrivateMessageRequest
	(*DeletePrivateMessageRequest)(nil), // 2: user.DeletePrivateMessageRequest
	(*ListMessageRequest)(nil),          // 3: user.ListMessageRequest
	(*Message)(nil),                     // 4: user.Message
	(*ListPrivateMessageResponse)(nil),  // 5: user.ListPrivateMessageResponse
	(*ListMessageResponse)(nil),         // 6: user.ListMessageResponse
	(*StudentLoginRequest)(nil),         // 7: user.StudentLoginRequest
	(*UpdateInfoRequest)(nil),           // 8: user.UpdateInfoRequest
	(*GetRequest)(nil),                  // 9: user.GetRequest
	(*FollowRequest)(nil),               // 10: user.FollowRequest
	(*FollowResponse)(nil),              // 11: user.FollowResponse
	(*FollowListRequest)(nil),           // 12: user.FollowListRequest
	(*FollowListUser)(nil),              // 13: user.FollowListUser
	(*FollowListResponse)(nil),          // 14: user.FollowListResponse
	(*GetInfoRequest)(nil),              // 15: user.GetInfoRequest
	(*RegisterRequest)(nil),             // 16: user.RegisterRequest
	(*TeamLoginRequest)(nil),            // 17: user.TeamLoginRequest
	(*LoginResponse)(nil),               // 18: user.LoginResponse
	(*UserInfo)(nil),                    // 19: user.UserInfo
	(*UserInfoResponse)(nil),            // 20: user.UserInfoResponse
	(*UserProfile)(nil),                 // 21: user.UserProfile
	(*ListRequest)(nil),                 // 22: user.ListRequest
	(*ListResponse)(nil),                // 23: user.ListResponse
	(*Request)(nil),                     // 24: user.Request
	(*Response)(nil),                    // 25: user.Response
	(*User)(nil),                        // 26: user.User
	(*GetUserIdentityRequest)(nil),      // 27: user.GetUserIdentityRequest
	(*GetUserIdentityResponse)(nil),     // 28: user.GetUserIdentityResponse
}
var file_proto_user_proto_depIdxs = []int32{
	4,  // 0: user.ListPrivateMessageResponse.messages:type_name -> user.Message
	19, // 1: user.UpdateInfoRequest.info:type_name -> user.UserInfo
	13, // 2: user.FollowListResponse.users:type_name -> user.FollowListUser
	19, // 3: user.UserInfoResponse.list:type_name -> user.UserInfo
	26, // 4: user.ListResponse.list:type_name -> user.User
	17, // 5: user.UserService.TeamLogin:input_type -> user.TeamLoginRequest
	7,  // 6: user.UserService.StudentLogin:input_type -> user.StudentLoginRequest
	15, // 7: user.UserService.GetInfo:input_type -> user.GetInfoRequest
	9,  // 8: user.UserService.GetProfile:input_type -> user.GetRequest
	10, // 9: user.UserService.ToggleFollow:input_type -> user.FollowRequest
	12, // 10: user.UserService.ListFollowing:input_type -> user.FollowListRequest
	12, // 11: user.UserService.ListFollowers:input_type -> user.FollowListRequest
	22, // 12: user.UserService.List:input_type -> user.ListRequest
	3,  // 13: user.UserService.ListMessage:input_type -> user.ListMessageRequest
	3,  // 14: user.UserService.ListPrivateMessage:input_type -> user.ListMessageRequest
	0,  // 15: user.UserService.CreateMessage:input_type -> user.CreateMessageRequest
	1,  // 16: user.UserService.CreatePrivateMessage:input_type -> user.CreatePrivateMessageRequest
	2,  // 17: user.UserService.DeletePrivateMessage:input_type -> user.DeletePrivateMessageRequest
	2,  // 18: user.UserService.MarkPrivateMessageRead:input_type -> user.DeletePrivateMessageRequest
	8,  // 19: user.UserService.UpdateInfo:input_type -> user.UpdateInfoRequest
	27, // 20: user.UserService.GetUserIdentity:input_type -> user.GetUserIdentityRequest
	18, // 21: user.UserService.TeamLogin:output_type -> user.LoginResponse
	18, // 22: user.UserService.StudentLogin:output_type -> user.LoginResponse
	20, // 23: user.UserService.GetInfo:output_type -> user.UserInfoResponse
	21, // 24: user.UserService.GetProfile:output_type -> user.UserProfile
	11, // 25: user.UserService.ToggleFollow:output_type -> user.FollowResponse
	14, // 26: user.UserService.ListFollowing:output_type -> user.FollowListResponse
	14, // 27: user.UserService.ListFollowers:output_type -> user.FollowListResponse
	23, // 28: user.UserService.List:output_type -> user.ListResponse
	6,  // 29: user.UserService.ListMessage:output_type -> user.ListMessageResponse
	5,  // 30: user.UserService.ListPrivateMessage:output_type -> user.ListPrivateMessageResponse
	25, // 31: user.UserService.CreateMessage:output_type -> user.Response
	25, // 32: user.UserService.CreatePrivateMessage:output_type -> user.Response
	25, // 33: user.UserService.DeletePrivateMessage:output_type -> user.Response
	25, // 34: user.UserService.MarkPrivateMessageRead:output_type -> user.Response
	25, // 35: user.UserService.UpdateInfo:output_type -> user.Response
	28, // 36: user.UserService.GetUserIdentity:output_type -> user.GetUserIdentityResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
